CREATE DATABASE myproject;

CREATE TABLE USER (
	USER_ID     INT       NOT NULL  PRIMARY KEY AUTO_INCREMENT,
	NAME        VARCHAR(50)   NOT NULL,
	LOGIN       VARCHAR(50)   NOT NULL,
	PASSWORD    VARCHAR(50)   NOT NULL,
	TEST_RESULT DOUBLE
	);

INSERT INTO USER (USER_ID, NAME, LOGIN, PASSWORD, TEST_RESULT)
VALUES (1, "admin", "admin", "admin", 0);

INSERT INTO USER (USER_ID, NAME, LOGIN, PASSWORD, TEST_RESULT)
VALUES (2, "Sergey", "Shadow", "123", 0);

